[2025-07-21T03:04:29.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-21T03:04:29.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T03:04:26.803226+00:00 [queued]>
[2025-07-21T03:04:29.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T03:04:26.803226+00:00 [queued]>
[2025-07-21T03:04:29.350+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-21T03:04:29.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-21 03:04:26.803226+00:00
[2025-07-21T03:04:29.367+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_foreacst_dag', 'fetch_forecast', 'manual__2025-07-21T03:04:26.803226+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp72w0prhs']
[2025-07-21T03:04:29.369+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=220) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-21T03:04:29.370+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask fetch_forecast
[2025-07-21T03:04:29.371+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2025-07-21T03:04:29.409+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T03:04:26.803226+00:00 [running]> on host 5479cb0e4647
[2025-07-21T03:04:29.472+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_foreacst_dag' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-21T03:04:26.803226+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-21T03:04:26.803226+00:00'
[2025-07-21T03:04:29.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-21T03:04:29.483+0000] {weather_dag.py:49} INFO - Bắt đầu gọi API thời tiết...
[2025-07-21T03:04:40.229+0000] {weather_dag.py:122} ERROR - Lỗi khi ghi dữ liệu vào DB 1054 (42S22): Unknown column 'nan' in 'field list'
[2025-07-21T03:04:40.230+0000] {weather_dag.py:126} INFO - Đã insert 1200 dòng dữ liệu thời tiết
[2025-07-21T03:04:40.233+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-21T03:04:40.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-21T03:04:40.243+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_weather_foreacst_dag, task_id=fetch_forecast, run_id=manual__2025-07-21T03:04:26.803226+00:00, execution_date=20250721T030426, start_date=20250721T030429, end_date=20250721T030440
[2025-07-21T03:04:40.261+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-21T03:04:40.275+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-21T03:04:40.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
