[2025-07-19T08:38:45.778+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-19T08:38:45.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_forecast.fetch_forecast scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-19T08:38:45.804+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_forecast.fetch_forecast scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-19T08:38:45.805+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-19T08:38:45.817+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-19 00:00:00+00:00
[2025-07-19T08:38:45.825+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_forecast', 'fetch_forecast', 'scheduled__2025-07-19T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/fetch_weather_data.py', '--cfg-path', '/tmp/tmp9uh07d1_']
[2025-07-19T08:38:45.826+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=693) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-19T08:38:45.827+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask fetch_forecast
[2025-07-19T08:38:45.827+0000] {standard_task_runner.py:63} INFO - Started process 695 to run task
[2025-07-19T08:38:45.871+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_weather_forecast.fetch_forecast scheduled__2025-07-19T00:00:00+00:00 [running]> on host 0189e20d7959
[2025-07-19T08:38:45.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_forecast' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T00:00:00+00:00'
[2025-07-19T08:38:45.929+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-19T08:38:57.279+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-19T08:38:57.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-19T08:38:57.291+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_weather_forecast, task_id=fetch_forecast, run_id=scheduled__2025-07-19T00:00:00+00:00, execution_date=20250719T000000, start_date=20250719T083845, end_date=20250719T083857
[2025-07-19T08:38:57.330+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-19T08:38:57.344+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-19T08:38:57.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
