[2025-07-21T03:04:27.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-21T03:04:27.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast scheduled__2025-07-20T18:00:00+00:00 [queued]>
[2025-07-21T03:04:27.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast scheduled__2025-07-20T18:00:00+00:00 [queued]>
[2025-07-21T03:04:27.387+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-21T03:04:27.398+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-20 18:00:00+00:00
[2025-07-21T03:04:27.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_foreacst_dag', 'fetch_forecast', 'scheduled__2025-07-20T18:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp1xj3cc8a']
[2025-07-21T03:04:27.408+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask fetch_forecast
[2025-07-21T03:04:27.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-21T03:04:27.409+0000] {standard_task_runner.py:63} INFO - Started process 216 to run task
[2025-07-21T03:04:27.451+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_weather_foreacst_dag.fetch_forecast scheduled__2025-07-20T18:00:00+00:00 [running]> on host 5479cb0e4647
[2025-07-21T03:04:27.523+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_foreacst_dag' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-20T18:00:00+00:00'
[2025-07-21T03:04:27.525+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-21T03:04:27.535+0000] {weather_dag.py:49} INFO - Bắt đầu gọi API thời tiết...
[2025-07-21T03:04:38.333+0000] {weather_dag.py:122} ERROR - Lỗi khi ghi dữ liệu vào DB 1054 (42S22): Unknown column 'nan' in 'field list'
[2025-07-21T03:04:38.335+0000] {weather_dag.py:126} INFO - Đã insert 1200 dòng dữ liệu thời tiết
[2025-07-21T03:04:38.337+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-21T03:04:38.338+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-21T03:04:38.346+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_weather_foreacst_dag, task_id=fetch_forecast, run_id=scheduled__2025-07-20T18:00:00+00:00, execution_date=20250720T180000, start_date=20250721T030427, end_date=20250721T030438
[2025-07-21T03:04:38.377+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-21T03:04:38.389+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-21T03:04:38.392+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
