[2025-07-21T07:50:04.700+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-21T07:50:04.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T07:50:01.837795+00:00 [queued]>
[2025-07-21T07:50:04.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T07:50:01.837795+00:00 [queued]>
[2025-07-21T07:50:04.735+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-21T07:50:04.746+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_forecast> on 2025-07-21 07:50:01.837795+00:00
[2025-07-21T07:50:04.753+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_foreacst_dag', 'fetch_forecast', 'manual__2025-07-21T07:50:01.837795+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp5754ljpt']
[2025-07-21T07:50:04.756+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-21T07:50:04.757+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask fetch_forecast
[2025-07-21T07:50:04.757+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2025-07-21T07:50:04.799+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_weather_foreacst_dag.fetch_forecast manual__2025-07-21T07:50:01.837795+00:00 [running]> on host 57ad0942e679
[2025-07-21T07:50:04.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_foreacst_dag' AIRFLOW_CTX_TASK_ID='fetch_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-07-21T07:50:01.837795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-21T07:50:01.837795+00:00'
[2025-07-21T07:50:04.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-21T07:50:04.887+0000] {weather_dag.py:49} INFO - Bắt đầu gọi API thời tiết...
[2025-07-21T07:50:15.357+0000] {weather_dag.py:94} INFO - Các cột có giá trị None: name                           0
forecast_time                  0
temperature                    0
temperatureApparent            0
dewPoint                       0
humidity                       0
windSpeed                      0
windDirection                  0
windGust                       0
pressureSurfaceLevel           0
cloudCover                     0
precipitationProbability       0
uvIndex                      180
ezHeatStressIndex           1200
dtype: int64
[2025-07-21T07:50:15.363+0000] {weather_dag.py:98} WARNING - Cột name vẫn chứa chuỗi 'nan'!
[2025-07-21T07:50:15.381+0000] {weather_dag.py:98} WARNING - Cột uvIndex vẫn chứa chuỗi 'nan'!
[2025-07-21T07:50:15.460+0000] {weather_dag.py:129} ERROR - Lỗi khi ghi dữ liệu vào DB 1054 (42S22): Unknown column 'nan' in 'field list'
[2025-07-21T07:50:15.462+0000] {weather_dag.py:133} INFO - Đã insert 1200 dòng dữ liệu thời tiết
[2025-07-21T07:50:15.466+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-21T07:50:15.467+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-21T07:50:15.476+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_weather_foreacst_dag, task_id=fetch_forecast, run_id=manual__2025-07-21T07:50:01.837795+00:00, execution_date=20250721T075001, start_date=20250721T075004, end_date=20250721T075015
[2025-07-21T07:50:15.522+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-21T07:50:15.537+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-21T07:50:15.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
